spring:
  application:
    name: mym-expense-service
  data:
    mongodb:
      uri: ${mongo.uri}
      database: mym-expense-db

myEureka:
  username: 'rkumar0206'
  password: '123456789P'

eureka:
  client:
    service-url:
      defaultZone: http://${myEureka.username}:${myEureka.password}@localhost:8845/eureka
  instance:
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 30
    lease-renewal-interval-in-seconds: 30

server:
  port: 8687

pagination:
  maxPageSizeAllowed: 200

logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG

management:
  endpoints:
    web:
      exposure:
        include:
          - "*"
      base-path: "/mym/${spring.application.name}/actuator"